aero:
  batch:
    dropZone: /Users/nairr5/workspace/aero.ws/talend/aero-batch/drop-zone
    fileNamePattern: "*.DATA"
    outZone: /Users/nairr5/workspace/aero.ws/talend/aero-batch/out-zone
    fdrMappingFile: /Users/nairr5/workspace/aero.ws/talend/aero-batch/src/main/resources/fdr-edi-config.xml
    terminator:
      segmentTerminator: \x1C
      componentTerminator: \x1D
      elementTerminator: \x1F

spring:
  batch:
    job:
      enabled: false
  datasource:
    initialize: false
